[package]
name = "ict40010"
version = "0.1.0"
authors = ["David J Holland <stooge213@hotmail.com>"]
edition = "2018"

[dependencies]
gl = "0.14.0"
anyhow = "1.0.27"
nalgebra-glm = "0.6.0"
memoffset = "0.5.4"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"

[lib]
name = "glamour"
path = "src/glamour/lib.rs"

[[bin]]
name = "sandbox"
path = "src/sandbox/bin.rs"
