name: Rust

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo build

    - name: Test
      run: cargo test

  docs:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Glamour Docs
      run: |
        cargo doc --lib --no-deps --target-dir ./docs/.vuepress/public/
        rm -rf ./docs/.vuepress/public/debug ./docs/.vuepress/public/.rustc_info.json

    - name: Build Vuepress Docs
      run: |
        yarn --frozen-lockfile
        yarn build

    # - name: Deploy Docs
    #   run: |
    #     # navigate into the build output directory
    #     cd ./docs/.vuepress/dist

    #     # if you are deploying to a custom domain
    #     # echo 'www.example.com' > CNAME

    #     git init
    #     git add -A
    #     git commit -m '🚀 deploy docs 📝'

    #     # if you are deploying to https://<USERNAME>.github.io/<REPO>
    #     git push -f git@github.com:smeagolem/ict40010.git master:gh-pages

    #     cd -

    - name: Deploy Docs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GLAMOUR_DOCS_DEPLOY }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: ./docs/.vuepress/dist # The folder the action should deploy.
        COMMIT_MESSAGE: 🚀 deploy docs 📝

